export const GENERATE_NOTES = 'GENERATE_NOTES';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const ADD_NOTE_AMOUNT = 'ADD_NOTE_AMOUNT';
export const REMOVE_NOTE_AMOUNT = 'REMOVE_NOTE_AMOUNT';
export const SET_PLAYING_NOTE = 'SET_PLAYING_NOTE';
export const CLEAR_PLAYING_NOTES = 'CLEAR_PLAYING_NOTES';
