export const GENERATE_NOTES = 'GENERATE_NOTES';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const ADD_NOTE_AMOUNT = 'ADD_NOTE_AMOUNT';
export const REMOVE_NOTE_AMOUNT = 'REMOVE_NOTE_AMOUNT';
